# Generated by Django 3.1.12 on 2021-06-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='name',
            field=models.CharField(default='Wallet', max_length=100),
        ),
    ]
