# Generated by Django 3.1.12 on 2021-06-24 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_walletuser_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Тип Записи',
                'verbose_name_plural': 'Типы Записей',
                'db_table': 'note_type',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('income', models.BooleanField()),
                ('receipt', models.ImageField(upload_to='')),
                ('input_date', models.DateTimeField()),
                ('constant', models.BooleanField()),
                ('description', models.CharField(max_length=100)),
                ('over_date', models.DateField()),
                ('note_type', models.ForeignKey(default='прочее', on_delete=django.db.models.deletion.SET_DEFAULT, to='app.notetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'db_table': 'note',
            },
        ),
    ]
