# Generated by Django 3.1.12 on 2021-06-25 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_note_notetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='constant',
        ),
        migrations.RemoveField(
            model_name='note',
            name='income',
        ),
        migrations.AddField(
            model_name='note',
            name='is_closed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notetype',
            name='constant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notetype',
            name='income',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='NotePaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateTimeField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.note')),
            ],
        ),
    ]
