# Generated by Django 3.1.12 on 2021-07-01 08:33

import app.models.user_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210626_0203'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='walletuser',
            managers=[
                ('objects', app.models.user_model.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='walletuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts\\'),
        ),
        migrations.CreateModel(
            name='UnverifiedUserCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unverified_user_code',
            },
        ),
    ]
