# Generated by Django 3.1.12 on 2021-07-01 02:44

import app.models.user_model
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210701_0219'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='walletuser',
            managers=[
                ('objects', app.models.user_model.UserManager()),
            ],
        ),
        migrations.AlterModelTable(
            name='unverifiedusercode',
            table='unverified_user_code',
        ),
    ]
