# Generated by Django 3.1.12 on 2021-07-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210701_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unverifiedusercode',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
