 repos:
  - repo: local
    hooks:
      - id: django-test
        name: django-test
        entry: python src/manage.py test
        always_run: true
        pass_filenames: false
        language: system